[package]
name = "rsp-program"
version = "1.1.0"
edition = "2021"
publish = false

[dependencies]
sp1-zkvm = "2.0.0"
bincode = "1.3.3"
polccint-lib = { path = "../../lib" }
rsp-client-executor = { git = "https://github.com/succinctlabs/rsp/", rev = "792efd0" }