ForkUpgradeBatchNumber = 0
ForkUpgradeNewForkId = 0

[Common]
NetworkID = 1
IsValidiumMode = false
ContractVersions = "banana"

[Etherman]
URL = "http://test-fep-type1-l1:8545"

[Log]
Environment = "development" # "production" or "development"
Level = "info"
Outputs = ["stderr"]

[ReorgDetectorL1]
DBPath = "/tmp/reorgdetectorl1"

[ReorgDetectorL2]
DBPath = "/tmp/reorgdetectorl2"
CheckReorgsInterval="1h"

[L1InfoTreeSync]
DBPath = "/tmp/L1InfoTreeSync"
GlobalExitRootAddr="0x8A791620dd6260079BF849Dc5567aDC3F2FdC318"
RollupManagerAddr="0xB7f8BC63BbcaD18155201308C8f3540b07f84F5e" 
SyncBlockChunkSize=10
BlockFinality="LatestBlock"
URLRPCL1="http://test-fep-type1-l1:8545"
WaitForNewBlocksPeriod="100ms"
InitialBlock=0

[AggOracle]
TargetChainType="EVM"
URLRPCL1="http://test-fep-type1-l2:8545"
BlockFinality="FinalizedBlock"
WaitPeriodNextGER="1s"
	[AggOracle.EVMSender]
		GlobalExitRootL2="0xd7f3718473c5Ea7646282DCa55ab1abEe4f6B27a"
		URLRPCL2="http://test-fep-type1-l2:8545"
		ChainIDL2=42069
		GasOffset=0
		WaitPeriodMonitorTx="1s"
		SenderAddr="0x70997970c51812dc3a010c7d01b50e0d17dc79c8"
		[AggOracle.EVMSender.EthTxManager]
				FrequencyToMonitorTxs = "1s"
				WaitTxToBeMined = "1s"
				GetReceiptMaxTime = "1s"
				GetReceiptWaitInterval = "1s"
				PrivateKeys = [
					{Path = "/app/keystore/aggoracle.keystore", Password = "testonly"},
				]
				ForcedGas = 0
				GasPriceMarginFactor = 1
				MaxGasPriceLimit = 0
				PersistenceFilename = "/tmp/ethtxmanager-sequencesender.json"
				ReadPendingL1Txs = false
				SafeStatusL1NumberOfBlocks = 5
				FinalizedStatusL1NumberOfBlocks = 10
					[AggOracle.EVMSender.EthTxManager.Etherman]
						URL = "http://test-fep-type1-l2:8545"
						MultiGasProvider = false
						L1ChainID = 42069
						HTTPHeaders = []

[RPC]
Host = "0.0.0.0"
Port = 5576
ReadTimeout = "2s"
WriteTimeout = "2s"
MaxRequestsPerIPAndSecond = 10

[ClaimSponsor]
DBPath = "/tmp/claimsopnsor"
Enabled = true
SenderAddr = "0x976ea74026e726554db657fa54763abd0c3a0aa9"
BridgeAddrL2 = "0xB0b0cE3949B4B3528cC013A2F305527E571d17Ba"
MaxGas = 200000
RetryAfterErrorPeriod = "1s"
MaxRetryAttemptsAfterError = -1
WaitTxToBeMinedPeriod = "3s"
WaitOnEmptyQueue = "3s"
GasOffset = 0
	[ClaimSponsor.EthTxManager]
		FrequencyToMonitorTxs = "1s"
		WaitTxToBeMined = "2s"
		GetReceiptMaxTime = "250ms"
		GetReceiptWaitInterval = "1s"
		PrivateKeys = [
			{Path = "/app/keystore/claimsponsor.keystore", Password = "testonly"},
		]
		ForcedGas = 0
		GasPriceMarginFactor = 1
		MaxGasPriceLimit = 0
		PersistenceFilename = "/tmp/ethtxmanager-claimsopnsor.json"
		ReadPendingL1Txs = false
		SafeStatusL1NumberOfBlocks = 5
		FinalizedStatusL1NumberOfBlocks = 10
			[ClaimSponsor.EthTxManager.Etherman]
				URL = "http://test-fep-type1-l2:8545"
				MultiGasProvider = false
				L1ChainID = 1337
				HTTPHeaders = []

[L1Bridge2InfoIndexSync]
DBPath = "/tmp/l1bridge2infoindexsync"
RetryAfterErrorPeriod = "1s"
MaxRetryAttemptsAfterError = -1
WaitForSyncersPeriod = "3s"

[BridgeL1Sync]
DBPath = "/tmp/bridgel1sync"
BlockFinality = "LatestBlock"
InitialBlockNum = 0
BridgeAddr = "0xFe12ABaa190Ef0c8638Ee0ba9F828BF41368Ca0E"
SyncBlockChunkSize = 100
RetryAfterErrorPeriod = "1s"
MaxRetryAttemptsAfterError = -1
WaitForNewBlocksPeriod = "3s"

[BridgeL2Sync]
DBPath = "/tmp/bridgel2sync"
BlockFinality = "LatestBlock"
InitialBlockNum = 0
BridgeAddr = "0xB0b0cE3949B4B3528cC013A2F305527E571d17Ba"
SyncBlockChunkSize = 100
RetryAfterErrorPeriod = "1s"
MaxRetryAttemptsAfterError = -1
WaitForNewBlocksPeriod = "3s"

[LastGERSync]
DBPath = "/tmp/lastgersync"
BlockFinality = "LatestBlock"
InitialBlockNum = 0
GlobalExitRootL2Addr = "0xd7f3718473c5Ea7646282DCa55ab1abEe4f6B27a"
RetryAfterErrorPeriod = "1s"
MaxRetryAttemptsAfterError = -1
WaitForNewBlocksPeriod = "1s"
DownloadBufferSize = 100


[SequenceSender]
WaitPeriodSendSequence = "1500h"
LastBatchVirtualizationTimeMaxWaitPeriod = "1500h"
L1BlockTimestampMargin = "1500h"
MaxTxSizeForL1 = 13107200000000
L2Coinbase = "0xfa3b44587990f97ba8b6ba7e230a5f0e95d14b3d"
PrivateKey = {Path = "/app/keystore/claimsponsor.keystore", Password = "testonly"}
SequencesTxFileName = "sequencesender.json"
GasOffset = 80000
WaitPeriodPurgeTxFile = "1500h"
MaxPendingTx = 1
MaxBatchesForL1 = 30000000000
BlockFinality = "FinalizedBlock"
RPCURL = ""
GetBatchWaitInterval = "1500h"
	[SequenceSender.EthTxManager]
		FrequencyToMonitorTxs = "1500h"
		WaitTxToBeMined = "1500h"
		GetReceiptMaxTime = "1500h"
		GetReceiptWaitInterval = "11500h"
		PrivateKeys = [
			{Path = "/app/keystore/claimsponsor.keystore", Password = "testonly"},
		]
		ForcedGas = 0
		GasPriceMarginFactor = 1
		MaxGasPriceLimit = 0
		PersistenceFilename = "ethtxmanager.json"
		ReadPendingL1Txs = false
		SafeStatusL1NumberOfBlocks = 0
		FinalizedStatusL1NumberOfBlocks = 0
			[SequenceSender.EthTxManager.Etherman]
				URL = "http://test-fep-type1-l1:8545"
				MultiGasProvider = false
				L1ChainID = 1337


[NetworkConfig.L1]
L1ChainID = 1337
PolAddr = "0x0000000000000000000000000000000000000000"
ZkEVMAddr = "0x8dAF17A20c9DBA35f005b6324F493785D239719d"
RollupManagerAddr = "0xB7f8BC63BbcaD18155201308C8f3540b07f84F5e"
GlobalExitRootManagerAddr = "0x8A791620dd6260079BF849Dc5567aDC3F2FdC318"