[Log]
Environment = "development" # "production" or "development"
Level = "debug"
Outputs = ["stderr"]

[Common]
NetworkID = 1
IsValidiumMode = false
ContractVersions = "banana"

[Etherman]
URL = "http://test-aggoracle-l1:8545"

[ReorgDetectorL1]
DBPath = "/tmp/reorgdetectorL1"

[ReorgDetectorL2]
DBPath = "/tmp/reorgdetectorL2"

[L1InfoTreeSync]
DBPath = "/tmp/L1InfoTreeSync"
GlobalExitRootAddr="0x8A791620dd6260079BF849Dc5567aDC3F2FdC318"
SyncBlockChunkSize=10
BlockFinality="LatestBlock"
URLRPCL1="http://test-aggoracle-l1:8545"
WaitForNewBlocksPeriod="100ms"
InitialBlock=0

[AggOracle]
TargetChainType="EVM"
URLRPCL1="http://test-aggoracle-l1:8545"
BlockFinality="LatestBlock"
WaitPeriodNextGER="3s"
    [AggOracle.EVMSender]
        GlobalExitRootL2="0x11e88480675aC990d53a1707Eb2535ee4E92c810"
        URLRPCL2="http://test-aggoracle-l2:8545"
        ChainIDL2=1337
        GasOffset=0
        WaitPeriodMonitorTx="1s"
        SenderAddr="0x70997970c51812dc3a010c7d01b50e0d17dc79c8"
        [AggOracle.EVMSender.EthTxManager]
                FrequencyToMonitorTxs = "1s"
                WaitTxToBeMined = "2s"
                GetReceiptMaxTime = "250ms"
                GetReceiptWaitInterval = "1s"
                PrivateKeys = [
                    {Path = "/app/keystore/aggoracle.keystore", Password = "testonly"},
                ]
                ForcedGas = 0
                GasPriceMarginFactor = 1
                MaxGasPriceLimit = 0
                PersistenceFilename = "/tmp/ethtxmanager.json"
                ReadPendingL1Txs = false
                SafeStatusL1NumberOfBlocks = 5
                FinalizedStatusL1NumberOfBlocks = 10
                    [AggOracle.EVMSender.EthTxManager.Etherman]
                        URL = "http://test-aggoracle-l2:8545"
                        MultiGasProvider = false
                        L1ChainID = 1337
                        HTTPHeaders = []


[RPC]
Host = "0.0.0.0"
Port = 5576
ReadTimeout = "2s"
WriteTimeout = "2s"
MaxRequestsPerIPAndSecond = 1000

[ClaimSponsor]
DBPath = "/tmp/claimsopnsor"
Enabled = true
SenderAddr = "0xfa3b44587990f97ba8b6ba7e230a5f0e95d14b3d"
BridgeAddrL2 = "0x40BbC3C932dcdb26A108e5e249F1800047dCc947"
MaxGas = 200000
RetryAfterErrorPeriod = "1s"
MaxRetryAttemptsAfterError = 0
WaitTxToBeMinedPeriod = "3s"
WaitOnEmptyQueue = "3s"
GasOffset = 0
	[ClaimSponsor.EthTxManager]
		FrequencyToMonitorTxs = "5s"
		WaitTxToBeMined = "5s"
		GetReceiptMaxTime = "250ms"
		GetReceiptWaitInterval = "5s"
		PrivateKeys = [
			{Path = "/app/keystore/claimsponsor.keystore", Password = "testonly"},
		]
		ForcedGas = 0
		GasPriceMarginFactor = 1
		MaxGasPriceLimit = 0
		PersistenceFilename = "/tmp/ethtxmanager-claimsopnsor.json"
		ReadPendingL1Txs = false
		SafeStatusL1NumberOfBlocks = 5
		FinalizedStatusL1NumberOfBlocks = 10
			[ClaimSponsor.EthTxManager.Etherman]
				URL = "http://test-aggoracle-l2:8545"
				MultiGasProvider = false
				L1ChainID = 1337
				HTTPHeaders = []

[L1Bridge2InfoIndexSync]
DBPath = "/tmp/l1bridge2infoindexsync"
RetryAfterErrorPeriod = "1s"
MaxRetryAttemptsAfterError = 0
WaitForSyncersPeriod = "3s"

[BridgeL1Sync]
DBPath = "/tmp/bridgel1sync"
BlockFinality = "LatestBlock"
InitialBlockNum = 0
BridgeAddr = "0xFe12ABaa190Ef0c8638Ee0ba9F828BF41368Ca0E"
SyncBlockChunkSize = 100
RetryAfterErrorPeriod = "1s"
MaxRetryAttemptsAfterError = 0
WaitForNewBlocksPeriod = "3s"

[BridgeL2Sync]
DBPath = "/tmp/bridgel2sync"
BlockFinality = "LatestBlock"
InitialBlockNum = 0
BridgeAddr = "0x40BbC3C932dcdb26A108e5e249F1800047dCc947"
SyncBlockChunkSize = 100
RetryAfterErrorPeriod = "1s"
MaxRetryAttemptsAfterError = 0
WaitForNewBlocksPeriod = "3s"

[LastGERSync]
DBPath = "/tmp/lastgersync"
BlockFinality = "LatestBlock"
InitialBlockNum = 0
GlobalExitRootL2Addr = "0x11e88480675aC990d53a1707Eb2535ee4E92c810"
RetryAfterErrorPeriod = "1s"
MaxRetryAttemptsAfterError = 0
WaitForNewBlocksPeriod = "1s"
DownloadBufferSize = 100
