services:
  test-op-cdk:
    container_name: test-op-cdk
    restart: no
    image: arnaubennassar/cdk:12b8e2c
    platform: linux/amd64
    volumes:
      - ./config/cdk.toml:/app/config.toml
      # - ./config/l1genesis.json:/app/genesis.json
      - ./config/aggoracle.keystore:/app/keystore/aggoracle.keystore
      - ./config/claimsponsor.keystore:/app/keystore/claimsponsor.keystore
    ports:
      - 5576:5576
    command:
      - "/bin/sh"
      - "-c"
      - "cdk-node run --cfg /app/config.toml --custom-network-file /app/genesis.json --components aggoracle,rpc"
