ForkUpgradeBatchNumber = 0
ForkUpgradeNewForkId = 0

[Common]
NetworkID = 1
IsValidiumMode = false
ContractVersions = "banana"

[Etherman]
URL = "XXX_RPCL1_XXX"

[Log]
Environment = "development" # "production" or "development"
Level = "debug"
Outputs = ["stderr"]

[ReorgDetectorL1]
DBPath = "/tmp/reorgdetectorl1"
CheckReorgsInterval="1h"

[ReorgDetectorL2]
DBPath = "/tmp/reorgdetectorl2"
CheckReorgsInterval="1h"

[L1InfoTreeSync]
DBPath = "/tmp/L1InfoTreeSync"
GlobalExitRootAddr="XXX_GERL1_XXX"
RollupManagerAddr="XXX_ROLLUPMAN_XXX" 
SyncBlockChunkSize=100
BlockFinality="LatestBlock"
URLRPCL1="XXX_RPCL1_XXX"
WaitForNewBlocksPeriod="60s"
InitialBlock=XXX_INITBLOCK_L1_XXX

[AggOracle]
TargetChainType="EVM"
URLRPCL1="XXX_RPCL1_XXX"
BlockFinality="FinalizedBlock"
WaitPeriodNextGER="60s"
	[AggOracle.EVMSender]
		GlobalExitRootL2="XXX_GERL2_XXX"
		URLRPCL2="XXX_RPCL2_XXX"
		ChainIDL2=XXX_CHAINIDL2_XXX
		GasOffset=0
		WaitPeriodMonitorTx="60s"
		SenderAddr="XXX_AGGORACLESENDERADDR_XXX"
		[AggOracle.EVMSender.EthTxManager]
				FrequencyToMonitorTxs = "60s"
				WaitTxToBeMined = "60s"
				GetReceiptMaxTime = "60s"
				GetReceiptWaitInterval = "60s"
				PrivateKeys = [
					{Path = "/app/keystore/aggoracle.keystore", Password = "XXX_AGGORACLEKEYPASS_XXX"},
				]
				ForcedGas = 0
				GasPriceMarginFactor = 1
				MaxGasPriceLimit = 0
				PersistenceFilename = "/tmp/ethtxmanager-sequencesender.json"
				ReadPendingL1Txs = false
				SafeStatusL1NumberOfBlocks = 5
				FinalizedStatusL1NumberOfBlocks = 10
					[AggOracle.EVMSender.EthTxManager.Etherman]
						URL = "XXX_RPCL2_XXX"
						MultiGasProvider = false
						L1ChainID = XXX_CHAINIDL2_XXX
						HTTPHeaders = []

[RPC]
Host = "0.0.0.0"
Port = 5576
ReadTimeout = "10s"
WriteTimeout = "10s"
MaxRequestsPerIPAndSecond = 100

[ClaimSponsor]
DBPath = "/tmp/claimsopnsor"
Enabled = true
SenderAddr = "XXX_CLAIMSPONSORSENDERADDR_XXX"
BridgeAddrL2 = "XXX_BRIDGEL2_XXX"
MaxGas = 200000
RetryAfterErrorPeriod = "10s"
MaxRetryAttemptsAfterError = -1
WaitTxToBeMinedPeriod = "60s"
WaitOnEmptyQueue = "3s"
GasOffset = 0
	[ClaimSponsor.EthTxManager]
		FrequencyToMonitorTxs = "60s"
		WaitTxToBeMined = "60s"
		GetReceiptMaxTime = "60s"
		GetReceiptWaitInterval = "60s"
		PrivateKeys = [
			{Path = "/app/keystore/claimsponsor.keystore", Password = "XXX_CLAIMSPONSORKEYPASS_XXX"},
		]
		ForcedGas = 0
		GasPriceMarginFactor = 1
		MaxGasPriceLimit = 0
		PersistenceFilename = "/tmp/ethtxmanager-claimsopnsor.json"
		ReadPendingL1Txs = false
		SafeStatusL1NumberOfBlocks = 5
		FinalizedStatusL1NumberOfBlocks = 10
			[ClaimSponsor.EthTxManager.Etherman]
				URL = "XXX_RPCL2_XXX"
				MultiGasProvider = false
				L1ChainID = XXX_CHAINIDL2_XXX
				HTTPHeaders = []

[BridgeL1Sync]
DBPath = "/tmp/bridgel1sync"
BlockFinality = "LatestBlock"
InitialBlockNum = XXX_INITBLOCK_L1_XXX
BridgeAddr = "XXX_BRIDGEL1_XXX"
SyncBlockChunkSize = 1000
RetryAfterErrorPeriod = "10s"
MaxRetryAttemptsAfterError = -1
WaitForNewBlocksPeriod = "60s"
DownloadBufferSize = 1000

[BridgeL2Sync]
DBPath = "/tmp/bridgel2sync"
BlockFinality = "LatestBlock"
InitialBlockNum = XXX_INITBLOCK_L2_XXX
BridgeAddr = "XXX_BRIDGEL2_XXX"
RetryAfterErrorPeriod = "10s"
MaxRetryAttemptsAfterError = -1
WaitForNewBlocksPeriod = "60s"
DownloadBufferSize = 1000
SyncBlockChunkSize = 1000

[LastGERSync]
DBPath = "/tmp/lastgersync"
BlockFinality = "LatestBlock"
InitialBlockNum = 0 # TODO
GlobalExitRootL2Addr = "XXX_GERL2_XXX"
RetryAfterErrorPeriod = "10s"
MaxRetryAttemptsAfterError = -1
WaitForNewBlocksPeriod = "60s"
DownloadBufferSize = 1000
SyncBlockChunkSize = 1000


# [SequenceSender]
# WaitPeriodSendSequence = "1500h"
# LastBatchVirtualizationTimeMaxWaitPeriod = "1500h"
# L1BlockTimestampMargin = "1500h"
# MaxTxSizeForL1 = 13107200000000
# L2Coinbase = "0xfa3b44587990f97ba8b6ba7e230a5f0e95d14b3d"
# PrivateKey = {Path = "/app/keystore/claimsponsor.keystore", Password = "testonly"}
# SequencesTxFileName = "sequencesender.json"
# GasOffset = 80000
# WaitPeriodPurgeTxFile = "1500h"
# MaxPendingTx = 1
# MaxBatchesForL1 = 30000000000
# BlockFinality = "FinalizedBlock"
# RPCURL = ""
# GetBatchWaitInterval = "1500h"
# 	[SequenceSender.EthTxManager]
# 		FrequencyToMonitorTxs = "1500h"
# 		WaitTxToBeMined = "1500h"
# 		GetReceiptMaxTime = "1500h"
# 		GetReceiptWaitInterval = "11500h"
# 		PrivateKeys = [
# 			{Path = "/app/keystore/claimsponsor.keystore", Password = "testonly"},
# 		]
# 		ForcedGas = 0
# 		GasPriceMarginFactor = 1
# 		MaxGasPriceLimit = 0
# 		PersistenceFilename = "ethtxmanager.json"
# 		ReadPendingL1Txs = false
# 		SafeStatusL1NumberOfBlocks = 0
# 		FinalizedStatusL1NumberOfBlocks = 0
# 			[SequenceSender.EthTxManager.Etherman]
# 				URL = "http://test-fep-type1-l1:8545"
# 				MultiGasProvider = false
# 				L1ChainID = 1337


[NetworkConfig.L1]
L1ChainID = XXX_CHAINIDL1_XXX
PolAddr = "0x0000000000000000000000000000000000000000"
ZkEVMAddr = "XXX_ROLLUPADDR_XXX"
RollupManagerAddr = "XXX_ROLLUPMAN_XXX"
GlobalExitRootManagerAddr = "XXX_GERL1_XXX"