[package]
name = "aggregation-final-client"
version = "1.1.0"
edition = "2021"
publish = false

[dependencies]
bincode.workspace = true
sp1-zkvm.workspace = true
polccint-lib = { path = "../../../lib" }
sha2.workspace = true
alloy-sol-types.workspace = true
alloy-primitives.workspace = true